version: '2'

services:

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_USER: admin
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: OBDB

  observium:
    image: henningkessler/observium
    volumes:
      - observium:/opt/observium/rrd/
      - ./config.php:/opt/observium/config.php:ro
    restart: always
    ports:
      - "8000:80"
    links:
      - mariadb
    #extra_hosts:
    #  - "somehost:162.242.195.82"
    #  - "otherhost:50.31.209.229"

  nagios:
    image: jasonrivers/nagios
    restart: always
    ports:
      - "8001:80"

volumes:
  mariadb:
  observium: