version: '2'

services:

  observium:
    image: henningkessler/observium
    restart: always
    ports:
      - "8000:80"

  nagios:
    image: jasonrivers/nagios
    restart: always
    ports:
      - "8001:80"