version: '2'

services:

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_USER: admin
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: OBDB

  observium:
    image: henningkessler/observium
    volumes:
    - ./config.php:/opt/observium/config.php:ro
    restart: always
    ports:
      - "8000:80"
    links:
      - mariadb
    command: bash /opt/observium/discovery.php -u

  nagios:
    image: jasonrivers/nagios
    restart: always
    ports:
      - "8001:80"

volumes:
   mariadb: